<?php
/**
 * @file
 * Code for the GSB Feature News Display feature.
 */

include_once 'gsb_feature_news_display.features.inc';


/**
 * Implements hook_field_extra_fields().
 */
function gsb_feature_news_display_field_extra_fields() {

  $content_types = array('idea_story', 'announcement', 'school_story');
  foreach ($content_types as $content_type) {
    $extra['node'][$content_type]['display']['gsb_media_inquiries'] = array(
      'label' => t('Media Inquiries'),
      'description' => t('Display media inquiries text.'),
      'weight' => 30,
    );
  }

  return $extra;
}

/**
 * Implements hook_node_view().
 */
function gsb_feature_news_display_node_view($node, $view_mode, $langcode) {
  // If this field is not configured for this view mode, skip it.
  $fields = field_extra_fields_get_display('node', $node->type, $view_mode);
  if (empty($fields['gsb_media_inquiries']['visible'])) {
    return;
  }

  $media_inquiries_text = variable_get('gsb_media_inquiries_text', '');

  $node->content['gsb_media_inquiries'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'media-inquiries',
      ),
    ),
    '#children' => filter_xss($media_inquiries_text),
  );
}

/**
 * Implements hook_form_alter().
 */
function gsb_feature_news_display_form_alter(&$form, &$form_state) {
  if ($form['#form_id'] == 'gsb_feature_idea_story_display_config_top_stories') {
    $form['gsb_media_inquiries_text'] = array(
      '#type' => 'textarea',
      '#title' => t('Media inquiries text'),
      '#default_value' => variable_get('gsb_media_inquiries_text'),
      '#weight' => -9,
    );
    $form['#submit'][] = 'gsb_feature_news_display_settings_form_submit';
  }
}

/**
  * Implements hook_form_FORM_ID_alter().
  */
function gsb_feature_news_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state) {

  if ($form_state['view']->name == 'gsb_faculty_insights_listing' && $form_state['view']->current_display == 'faculty_insights_listing') {
    $form['exposed']['filter-field_search_field_value']['#access'] = FALSE;
  }

  if ($form_state['view']->name == 'news_by_criteria' && $form_state['view']->current_display == 'panel_pane_1') {

    $conf = $form_state['conf'];

    $title_link_default_value = '';
    if (!empty($conf['title_link'])) {
      $title_link_default_value = $conf['title_link'];
    }
    else if (!empty($conf['exposed']['title_link'])) {
      $title_link_default_value = $conf['exposed']['title_link'];
    }

    $item['title_link'] = array(
      '#title' => t('URL'),
      '#type' => 'textfield',
      '#weight' => -99,
      '#default_value' => $title_link_default_value,
    );
    $form = gsb_misc_fixes_associative_insert($form, 'override_title', $item);

    // set the required * for the Type field
    $type_title = $form['exposed']['filter-type']['#title'];
    $form['exposed']['filter-type']['#title'] = $type_title .
      ' <span class="form-required" title="' . t('This field is required.') . '">*</span>';

    // change the display order of the exposed filter fields to the following:
    $ordered_filters = array(
      'filter-type',
      'filter-field_academic_area_unlimited_tid',
      'filter-field_business_insight_topic_tid',
      'filter-field_region_of_interest_tid',
      'filter-field_tag_tid',
      'filter-field_centers_research_programs_tid',
      'filter-field_program_unlimited_tid',
      'filter-field_part_of_rethink_value'
    );
    foreach($ordered_filters as $filter) {
      $temp = $form['exposed'][$filter];
      unset($form['exposed'][$filter]);
      $form['exposed'][$filter] = $temp;
    }

    $form['#submit'][] = 'gsb_news_by_criteria_pane_config_submit';
  }
}

/**
 * Submit handler for views_content_views_panes_content_type_edit_form.
 *  - Save title link field in pane config.
 */
function gsb_news_by_criteria_pane_config_submit($form, &$form_state) {
  // unset the older value which was being kept in the 'exposed' part of the form
  unset($form_state['conf']['exposed']['title_link']);
  $form_state['conf']['title_link'] = $form_state['values']['title_link'];
}

/**
 * Implements hook_panels_pane_content_alter().
 *  - Alter News by Criteria content pane title to be linked to a custom URL.
 */
function gsb_feature_news_display_panels_pane_content_alter($content, $pane, $args, $context) {
  if ($content && $content->subtype == 'news_by_criteria-panel_pane_1') {
    if (!empty($pane->configuration['title_link'])) {
      $content->title = l($content->title, $pane->configuration['title_link']);
    }
  }
}

/**
 * Submit handler for gsb_feature_idea_story_display_config_top_stories.
 *  - Save media inquiries text in variable.
 */
function gsb_feature_news_display_settings_form_submit($form, &$form_state) {
  variable_set('gsb_media_inquiries_text', $form_state['values']['gsb_media_inquiries_text']);
}

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_news_display_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['story_list_by_title'] = array(
    'label' => t('Story'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/story-list-by-title',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
