<?php
/**
 * @file
 * Code for the GSB Feature News Display feature.
 */

include_once 'gsb_feature_news_display.features.inc';


/**
 * Implements hook_field_extra_fields().
 */
function gsb_feature_news_display_field_extra_fields() {

  $content_types = array('idea_story', 'announcement', 'school_story');
  foreach ($content_types as $content_type) {
    $extra['node'][$content_type]['display']['gsb_media_inquiries'] = array(
      'label' => t('Media Inquiries'),
      'description' => t('Display media inquiries text.'),
      'weight' => 30,
    );
  }

  return $extra;
}

/**
 * Implements hook_node_view().
 */
function gsb_feature_news_display_node_view($node, $view_mode, $langcode) {
  // If this field is not configured for this view mode, skip it.
  $fields = field_extra_fields_get_display('node', $node->type, $view_mode);
  if (empty($fields['gsb_media_inquiries']['visible'])) {
    return;
  }

  $media_inquiries_text = variable_get('gsb_media_inquiries_text', '');

  $node->content['gsb_media_inquiries'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'media-inquiries',
      ),
    ),
    '#children' => filter_xss($media_inquiries_text),
  );
}

/**
 * Implements hook_form_alter().
 */
function gsb_feature_news_display_form_alter(&$form, &$form_state) {

  if ($form['#form_id'] == 'gsb_feature_idea_story_display_config_top_stories') {
    $form['gsb_media_inquiries_text'] = array(
      '#type' => 'textarea',
      '#title' => t('Media inquiries text'),
      '#default_value' => variable_get('gsb_media_inquiries_text'),
      '#weight' => -9,
    );

    $form['#submit'][] = 'gsb_feature_news_display_settings_form_submit';
  }

  // Alter News by Criteria pane config form to include link field for title.
  if ($form['#form_id'] == 'views_content_views_panes_content_type_edit_form') {

    if ($form_state['view']->name == 'gsb_faculty_insights_listing' && $form_state['view']->current_display == 'faculty_insights_listing') {
      $form['exposed']['filter-field_search_field_value']['#access'] = FALSE;
    }

    if ($form_state['view']->name == 'news_by_criteria' && $form_state['view']->current_display == 'panel_pane_1') {

      /*
      // set the nids argument field into the exposed portion of the config form
      $form['arguments']['nid']['#description'] = 'Separate Node IDs with commas and no spaces.';
      $form['exposed']['arguments'] = $form['arguments'];
      $form['exposed']['arguments']['#weight'] = -98;
      $form['arguments']['#access'] = FALSE;
      */
      
      // set the required * for the Type field       
      $type_title = $form['exposed']['filter-type']['#title'];
      $form['exposed']['filter-type']['#title'] = $type_title . 
        ' <span class="form-required" title="' . t('This field is required.') . '">*</span>';

      $conf = $form_state['conf'];
      $title_link_exposed = array();
      $title_link_exposed['title_link'] = array(
        '#title' => t('Title link'),
        '#type' => 'textfield',
        '#default_value' => !empty($conf['exposed']['title_link']) ? $conf['exposed']['title_link'] : '',
      );
      $form['exposed'] = array_merge($title_link_exposed, $form['exposed']);  
      
      //$form['#validate'][] = 'gsb_news_by_criteria_pane_config_validate';
      $form['#submit'][] = 'gsb_news_by_criteria_pane_config_submit';
    }
  }
}

/**
 * Validate handler for views_content_views_panes_content_type_edit_form.
 *  - Stores the arguments nid field values in pane config.
 */
/*
function gsb_news_by_criteria_pane_config_validate(&$form, &$form_state) {
  $form_state['values']['arguments']['nid'] = $form_state['values']['exposed']['arguments']['nid'];
}
*/

/**
 * Submit handler for views_content_views_panes_content_type_edit_form.
 *  - Save title link field in pane config.
 */
function gsb_news_by_criteria_pane_config_submit($form, &$form_state) {
  $form_state['conf']['exposed']['title_link'] = $form_state['values']['exposed']['title_link'];
}

/**
 * Implements hook_panels_pane_content_alter().
 *  - Alter News by Criteria content pane title to be linked to a custom URL.
 */
function gsb_feature_news_display_panels_pane_content_alter($content, $pane, $args, $context) {
  if ($content && $content->subtype == 'news_by_criteria-panel_pane_1') {
    if (!empty($pane->configuration['exposed']['title_link'])) {
      $content->title = l($content->title, $pane->configuration['exposed']['title_link']);
    }
  }
}

/**
 * Submit handler for gsb_feature_idea_story_display_config_top_stories.
 *  - Save media inquiries text in variable.
 */
function gsb_feature_news_display_settings_form_submit($form, &$form_state) {
  variable_set('gsb_media_inquiries_text', $form_state['values']['gsb_media_inquiries_text']);
}

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_news_display_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['story_list_by_title'] = array(
    'label' => t('Story'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/story-list-by-title',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
